version: "3.9"
services:
  python3-flask-app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    environment:
      FLASK_ENV: development
